/**
 * Unique location-inclusive intro copy for each category slug on the website.
 * These are used both on the category pages and for generating search engine metadata.
 */
export const categoryIntros: Record<string, string> = {
    'laptops': 'Explore premium laptops in Egmore, Chennai at Signature Computers. We offer an extensive selection of new and refurbished laptops from top brands like HP, Dell, and Lenovo. Whether for student use, professional development, or gaming, find the perfect device matching your budget with verified manufacturer warranty.',
    'desktops': 'Shop high-performance desktops at Signature Computers in Egmore, Chennai. Our catalog features reliable business computers, student desktops, and custom-built rigs designed for peak productivity. Every system is fully tested and includes doorstep delivery and local hardware support.',
    'workstations': 'Discover enterprise-grade workstations at Signature Computers, Egmore, Chennai. Built for intensive processing tasks, 3D rendering, and data analysis, our HP and Dell workstations deliver absolute reliability. Upgrade your corporate infrastructure with customizable hardware configurations today.',
    'monitors': 'Shop monitors in Egmore, Chennai at Signature Computers — from budget HP and Dell displays to 4K panels. Elevate your workspace with high-refresh-rate gaming monitors or color-accurate screens for editing. Enjoy local warranty support, in-store demo displays, and same-day pickup.',
    'memory-storage': 'Shop genuine high-performance memory and storage solutions at Signature Computers, Egmore, Chennai. We offer a full range of high-speed DDR4/DDR5 RAM, internal SSDs, external backup drives, and enterprise memory upgrades. Keep your systems running at optimal speeds with manufacturer-backed components.',
    'memory': 'Browse high-speed RAM and memory solutions at Signature Computers, Egmore, Chennai. Enhance your laptop, desktop, or workstation performance with genuine DDR4 and DDR5 memory modules from leading brands. Enjoy official brand warranty and expert installation support.',
    'storage': 'Explore reliable storage solutions at Signature Computers, Egmore, Chennai. We supply a comprehensive selection of internal SSDs (SATA & NVMe), high-capacity HDDs, and portable external hard drives. Protect your critical business data with authentic, manufacturer-backed storage.',
    'accessories': 'Enhance your digital setup with quality computer accessories at Signature Computers, Chennai. From laptop stands to USB hubs and external hard drives, we carry all the essentials. Visit our Egmore store for genuine, high-quality peripherals with direct brand warranty.',
    'cctv': 'Secure your home and business with advanced CCTV systems from Signature Computers, Egmore, Chennai. We offer high-definition cameras, DVRs, and complete surveillance setups for continuous monitoring. Get expert consultation, installation assistance, and maintenance service locally.',
    'keyboards': 'Find ergonomic and mechanical keyboards at Signature Computers, Egmore, Chennai. We stock premium options from HP, Dell, Logitech, and key gaming brands for comfortable typing and precision. Test different models in our showroom before making your final purchase.',
    'mouse': 'Select the perfect mouse for work or gaming at Signature Computers, Egmore, Chennai. Our collection features optical, wireless, and gaming mice designed for comfort and durability. Experience precise tracking and click feedback with genuine peripherals from top manufacturers.',
    'keyboard-mouse-combo': 'Browse keyboard and mouse combos at Signature Computers, Egmore, Chennai. We stock HP, Dell, and Logitech combos with in-store testing before you buy. Perfect for office workstations and home setups, these bundles offer reliable performance and excellent value.',
    'headphones': 'Discover premium headphones and headsets at Signature Computers, Egmore, Chennai. We carry noise-cancelling office headsets and immersive gaming headphones for crisp, clear audio. Enjoy high-quality sound and comfortable designs with full manufacturer warranty coverage.',
    'cables': 'Shop durable computer cables and display adapters at Signature Computers in Egmore, Chennai. We stock high-speed HDMI, DisplayPort, Ethernet, and USB-C cables to ensure stable connectivity. Get the exact adapter or cable you need today with local delivery options.',
    'power-adapters': 'Find genuine laptop and desktop power adapters at Signature Computers, Chennai. Compatible chargers for HP, Dell, Lenovo, and Asus available with same-day replacement service. Protect your expensive hardware from power fluctuations with certified original power bricks.',
    'bags': 'Protect your gear with premium laptop bags and backpacks at Signature Computers, Egmore, Chennai. We offer water-resistant, shockproof sleeves and backpacks designed for comfortable commuting. Find stylish and secure carrying solutions for notebooks of all screen sizes.',
    'docks': 'Expand your device connectivity with premium docking stations at Signature Computers, Egmore, Chennai. We feature USB-C and Thunderbolt docks compatible with HP, Dell, Lenovo, and MacBook. Connect multiple monitors, peripherals, and charge your laptop through a single cable.',
    'hubs': 'Expand your device connectivity with high-speed USB hubs and multi-port adapters at Signature Computers, Egmore, Chennai. We feature compact hubs compatible with HP, Dell, Lenovo, and MacBook. Connect multiple peripherals through a single USB-C or USB-A port.',
    'usb-flashdrives': 'Get reliable portable storage with high-speed USB flash drives at Signature Computers, Egmore, Chennai. We stock durable pendrives from SanDisk, HP, and Kingston in various capacities from 32GB to 256GB. Perfect for quick file transfers and local backups.',
    'dvd-writers': 'Find reliable external DVD writers, webcams, and other accessories at Signature Computers, Egmore, Chennai. Easily expand your laptop capabilities with external DVD optical drives and plug-and-play webcams.',
};
